# Same as Arico20_mm_mp_1.yaml but with smooth transition
fields:
  - "m-m"
  - "m-p"

halo_model: Arico20
fit_response: True


params:
  # Gas parameters
  theta_inn:
    prior: [1.e-2, 4.0]
    initial_value: 0.2
    latex_name: $\theta_\mathrm{inn}$
    ls: '-'

  theta_out:
    prior: [0.3, 8.0]
    initial_value: 2.
    latex_name: $\theta_\mathrm{out}$
    ls: '-'

  logM_inn:
    prior: [10, 17]
    initial_value: 13
    latex_name: $\log M_\mathrm{inn}$
    ls: '-'

  mu:
    prior: [0.1, 1]
    initial_value: 0.31
    latex_name: $\mu_\mathrm{i}$
    ls: '-'

  logM_c:
    prior: [10, 16]
    initial_value: 13
    latex_name: $\log M_\mathrm{c}$
    ls: '-'


  beta:
    prior: [0.1, 5]
    initial_value: 0.35
    latex_name: $\beta$
    ls: '--'

  eta:
    prior: [0.2, 5]
    initial_value: 0.5
    latex_name: $\eta$
    ls: '--'

  logM_r:
    prior: [12, 16]
    initial_value: 13.5
    latex_name: $\log M_\mathrm{r}$
    ls: '--'

  # beta_r:
  #   prior: [0.5, 5]
  #   initial_value: 2
  #   latex_name: $\beta_\mathrm{r}$
  #   ls: '--'

  theta_rg:
    prior: [0.1, 1]
    initial_value: 0.3
    latex_name: $\theta_\mathrm{rg}$
    ls: '--'


  sigma_rg:
    prior: [1.e-2, 5.e-1]
    initial_value: 0.1
    latex_name: $\sigma_\mathrm{rg}$
    ls: '--'


  # Star parameters
  logM1_0:
    prior: [9, 16]
    initial_value: 12
    latex_name: $\log M_{1,0}$
    ls: ':'

  M1_fsat:
    prior: [0.01, 4]
    initial_value: 1
    latex_name: $M_{1,\mathrm{fsat}}$
    ls: ':'

  eps_fsat:
    prior: [0.01, 4]
    initial_value: 1
    latex_name: $\epsilon_\mathrm{fsat}$
    ls: ':'

  # alpha_fsat:
  #   prior: [0.01, 4]
  #   initial_value: 1
  #   latex_name: $\alpha_\mathrm{fsat}$
  #   ls: ':'

  delta_fsat:
    prior: [0.01, 4]
    initial_value: 1
    latex_name: $\delta_\mathrm{fsat}$
    ls: ':'

  gamma_fsat:
    prior: [0.01, 4]
    initial_value: 1
    latex_name: $\gamma_\mathrm{fsat}$
    ls: ':'

  # Pressure parameters
  A_nt:
    prior: [0, 5.]
    initial_value: 0.495
    latex_name: $A_\mathrm{nt}$
    ls: '-.'

  transition_alpha:
    prior: [0.1, 1.5]
    initial_value: 0.7
    latex_name: $\alpha_\mathrm{smooth}$
