# Same as Mead20_mm_mp_1.yaml but with smooth transition
fields:
  - "m-m"
  - "m-p"

halo_model: Mead20
fit_response: True


mcmc:
  nwalkers: 40
  nsteps: 2000
  burnin: 0.8  # Fraction of total steps
  niter: 5  # Number of MCMC restarts
  parallel: MPI
  sampler: ultranest  # If setting to ultranest all other arguments are ignored

exclude_params:
 - eta
 - sigma_star

params:
params:
  eps1:
    prior: [-0.9, 3]
    initial_value: -0.1065
    latex_name: $\epsilon_1$
    ls: '-'

  eps2:
    prior: [-0.9, 3]
    initial_value: 0.2
    latex_name: $\epsilon_2$
    ls: '-'

  # Gas parameters
  logM_0:
    prior: [10, 16]
    initial_value: 13.59
    latex_name: $\log M_0$
    ls: '-'

  beta:
    prior: [0.1, 2.5]
    initial_value: 0.6
    latex_name: $\beta$
    ls: '-'

  Gamma:
    prior: [1.05, 3]
    initial_value: 1.17
    latex_name: $\Gamma$
    ls: '-'

  eta_b:
    prior: [0.1, 5]
    initial_value: 0.5
    latex_name: $\eta_b$
    ls: '-'

  # Star parameters
  A_star:
    prior: [0.02, 0.15]
    initial_value: 0.033
    latex_name: $A_*$
    ls: '-.'

  logM_star:
    prior: [10, 15]
    initial_value: 12.45
    latex_name: $\log M_*$
    ls: '-.'


  # Pressure parameters
  alpha:
    prior: [0, 1.5]
    initial_value: 0.847
    latex_name: $\alpha$
    ls: '--'

  logT_w:
    prior: [6, 7.5]
    initial_value: 6.65
    latex_name: $\log T_\mathrm{w}$
    ls: '--'

  # Transition parameters
  transition_alpha:
    prior: [0.1, 1.5]
    initial_value: 0.7
    latex_name: $\alpha_\mathrm{smooth}$